name = "Legacy Reborn"
author = "Permdog99 & Agari"
version = "TU1-1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b379a6d6747eb670989e19d043fd5bcd3ec8b52b4a2b1d81a2e90c21653bd466"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1"]
