name = "Legacy Reborn"
author = "Legacy Projects"
version = "TU1-1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "009f60da76f5eecb101e97fec5d297e98f45ee431e98da22a5444b9e6e7eae42"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1"]
