name = "Legacy Reborn"
author = "Legacy Projects"
version = "TU1-1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76bea0b8c58418a1b73c7057e452973471f83c230788d913642ba6582396e423"

[versions]
fabric = "0.15.11"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.1"]
